# Generated by Django 4.2.3 on 2023-07-22 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classunit',
            name='start_year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='classunit',
            name='study_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
