# Generated by Django 4.2.3 on 2023-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_remove_student_parent_alter_parent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='student',
        ),
    ]
