# Generated by Django 4.2.3 on 2023-07-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_remove_student_klasa_classunit_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classunit',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='class_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students_in_class', to='usersApp.classunit'),
            preserve_default=False,
        ),
    ]
