# Generated by Django 4.2.3 on 2023-07-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_remove_classunit_student_student_class_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='usersApp.parent'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classunit',
            unique_together={('start_year', 'study_year', 'letter_mark')},
        ),
    ]
