# Generated by Django 4.2.3 on 2023-07-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_alter_parent_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='usersApp.profile'),
            preserve_default=False,
        ),
    ]
