# Generated by Django 4.2.3 on 2023-07-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_remove_parent_student_student_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='parent',
        ),
    ]
