# Generated by Django 4.2.3 on 2023-07-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(limit_choices_to={'account_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usersApp.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(limit_choices_to={'account_type': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='usersApp.profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'account_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='usersApp.profile'),
        ),
    ]
