# Generated by Django 4.2.3 on 2023-07-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_alter_parent_student_alter_parent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usersApp.student'),
        ),
    ]
