# Generated by Django 4.2.3 on 2023-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=10),
        ),
    ]
