# Generated by Django 4.2.3 on 2023-08-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('start_school_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'unique_together': {('number', 'start_school_year')},
            },
        ),
        migrations.AddField(
            model_name='grades',
            name='semestr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='gradesApp.semester'),
            preserve_default=False,
        ),
    ]
