# Generated by Django 4.2.3 on 2023-08-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0003_rename_semestr_grades_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ('date',)},
        ),
    ]
