# Generated by Django 4.2.3 on 2023-08-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0004_alter_grades_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='submited_by',
            new_name='submitted_by',
        ),
    ]
