# Generated by Django 4.2.3 on 2023-07-31 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventApp', '0020_remove_lesson_day_remove_lesson_subject_and_more'),
        ('usersApp', '0007_alter_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_of_lesson', to='usersApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calendarApp.day')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventApp.subject')),
            ],
        ),
    ]
