# Generated by Django 4.2.3 on 2023-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_weeklyschedule_remove_planoflesson_class_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
        ),
    ]
