# Generated by Django 4.2.3 on 2023-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_lesson_class_name_alter_lesson_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default='2023-10-10'),
            preserve_default=False,
        ),
    ]
