# Generated by Django 4.2.3 on 2023-08-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0004_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
