# Generated by Django 4.2.3 on 2023-08-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0007_classroom_classroomreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreservation',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarApp.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarApp.classroom'),
        ),
    ]
