# Generated by Django 4.2.3 on 2023-08-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_alter_lesson_day_of_week'),
        ('calendarApp', '0011_lesson_teacher_reservation'),
    ]

    operations = [
    ]
