# Generated by Django 4.2.3 on 2023-07-23 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Math', 'Mathematic'), ('English', 'English'), ('', '')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_teachers', to='eventApp.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='usersApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_of_lesson', to='usersApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('lesson_title', models.CharField(max_length=250)),
                ('lesson_description', models.TextField()),
                ('class_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_class_unit', to='usersApp.classunit')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_subject', to='eventApp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_teacher', to='eventApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventApp.day')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Other', 'Inne'), ('Small Test', 'Kartkówka'), ('Test', 'Sprawdzian'), ('Essay', 'Wypracowanie'), ('Project', 'Projekt')])),
                ('realisation_time', models.DateField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_teacher', to='eventApp.lessonreport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='eventApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('is_present', models.BooleanField(default=False)),
                ('lesson_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventApp.lessonreport')),
            ],
        ),
    ]
