# Generated by Django 4.2.3 on 2023-07-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_profile_photo'),
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'account_type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='usersApp.profile'),
        ),
    ]
