# Generated by Django 4.2.3 on 2023-07-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonreport',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
