# Generated by Django 4.2.3 on 2023-07-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_delete_calendarevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Other', 'Inne'), ('Small Test', 'Kartkówka'), ('Test', 'Sprawdzian'), ('Essay', 'Wypracowanie'), ('Project', 'Projekt')])),
                ('realisation_time', models.DateField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_teacher', to='eventApp.lessonreport')),
                ('of_lesson', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_lesson', to='eventApp.lessonreport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='eventApp.subject')),
            ],
        ),
    ]
