# Generated by Django 4.2.3 on 2023-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_calendarevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('other', 'other'), ('small_test', 'small_test'), ('test', 'test'), ('essay', 'essay'), ('project', 'project')]),
        ),
    ]
