# Generated by Django 4.2.3 on 2023-07-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_profile_photo'),
        ('eventApp', '0003_remove_lessonreport_teacher_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_teachers', to='eventApp.subject')),
                ('user', models.OneToOneField(limit_choices_to={'account_type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='usersApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='lessonreport',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_teacher', to='eventApp.teacher'),
            preserve_default=False,
        ),
    ]
