# Generated by Django 4.2.3 on 2023-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0005_remove_calendarevents_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='of_lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_lesson', to='eventApp.lessonreport'),
        ),
    ]
