# Generated by Django 4.2.3 on 2023-07-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
        ('eventApp', '0006_alter_calendarevents_of_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevents',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='eventApp.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('other', 'Other'), ('small_test', 'Small_test'), ('test', 'Test'), ('essay', 'Essay'), ('project', 'Project')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'account_type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='usersApp.profile'),
        ),
    ]
