# Generated by Django 4.2.3 on 2023-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0007_calendarevents_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevents',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
