# Generated by Django 4.2.3 on 2023-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0008_calendarevents_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('other', 'Other'), ('small_test', 'Small test'), ('test', 'Test'), ('essay', 'Essay'), ('project', 'Project')]),
        ),
    ]
