# Generated by Django 4.2.3 on 2023-07-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0009_alter_calendarevents_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevents',
            old_name='of_lesson',
            new_name='connected_to_lesson',
        ),
    ]
