# Generated by Django 4.2.3 on 2023-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_teacher_lessonreport_teacher'),
        ('eventApp', '0010_rename_of_lesson_calendarevents_connected_to_lesson'),
    ]

    operations = [
    ]
