# Generated by Django 4.2.3 on 2023-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0011_merge_20230723_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('Other', 'other'), ('Small Test', 'small_test'), ('Test', 'test'), ('Essay', 'essay'), ('Project', 'project')]),
        ),
    ]
