# Generated by Django 4.2.3 on 2023-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0012_alter_calendarevents_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('other', 'Other'), ('small_Test', 'Small Test'), ('test', 'Test'), ('essay', 'Essay'), ('project', 'Project')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('math', 'Mathematic'), ('english', 'English'), ('', '')], default='', max_length=100),
        ),
    ]
