# Generated by Django 4.2.3 on 2023-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0014_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Mathematic', 'Mathematic'), ('English', 'English'), ('History', 'History'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemisty'), ('Philosophy', 'Philosophy'), ('', '')], default='', max_length=100, unique=True),
        ),
    ]
