# Generated by Django 4.2.3 on 2023-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0016_alter_calendarevents_connected_to_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Small Test', 'Small Test'), ('Test', 'Test'), ('Essay', 'Essay'), ('Project', 'Project')]),
        ),
    ]
