# Generated by Django 4.2.3 on 2023-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0017_alter_calendarevents_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_type',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson_type',
            field=models.ManyToManyField(related_name='subject_teachers', to='eventApp.subject'),
        ),
    ]
