# Generated by Django 4.2.3 on 2023-08-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventApp', '0024_alter_calendarevents_event_type'),
        ('usersApp', '0007_alter_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('grade_description', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('connected_to_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventApp.lessonreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.student')),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventApp.teacher')),
            ],
        ),
    ]
