# Generated by Django 4.2.3 on 2023-08-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_alter_student_parent'),
        ('teacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='usersApp.student'),
        ),
    ]
