# Generated by Django 4.2.3 on 2023-08-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0024_alter_calendarevents_event_type'),
        ('teacherApp', '0002_alter_grades_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='eventApp.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='connected_to_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_lesson', to='eventApp.lessonreport'),
        ),
    ]
