# Generated by Django 4.2.3 on 2023-08-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherApp', '0003_grades_subject_alter_grades_connected_to_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
